### ISSUE TITLE
Upload timestamp on mod page shows current date / time instead of upload date / time.

### ISSUE THREAD

**Issue by megalon** [lolPants/ModSaber#4]
## Platform
**This bug report concerns:**
- [x] Backend Server
- [x] Frontend Client

## Details
The upload time text next to the version text on each mod page should show the date / time that the mod was uploaded, but it instead shows the current date / time.

## Reproducing the Problem
View any mod page on ModSaber, and look at the timestamp next to the version text.
Example:
https://www.modsaber.org/mod/song-loader/5.0.2

## Further Detail
This shows the current time that I loaded this page.
![image](https://user-images.githubusercontent.com/27714637/50289741-8a758b80-041e-11e9-9b1a-93b86e94741e.png)

**Comment by lolPants** [comment]
Closed by 5db16d4db22bea82769f1eb2d0a5eabe0b6c228e
